name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
  pull_request_review_comment:
    types: [created]

concurrency:
  group:
    ${{ github.repository }}-${{ github.event.number || github.head_ref ||
    github.sha }}-${{ github.workflow }}-${{ github.event_name ==
    'pull_request_review_comment' && 'pr_comment' || 'pr' }}
  cancel-in-progress: ${{ github.event_name != 'pull_request_review_comment' }}

jobs:
  review:
    if: ${{ contains(github.event.head_commit.message, 'check-review') }} 
    runs-on: ubuntu-latest
    steps:
      - uses: coderabbitai/ai-pr-reviewer@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          debug: false
          review_simple_changes: false
          review_comment_lgtm: false
          openai_light_model: gpt-4
          openai_heavy_model: gpt-4
          language: ja-JP
          system_message: |
            あなたは @coderabbitai（別名 github-actions[bot]）で、OpenAIによって訓練された言語モデルです。
            あなたの目的は、非常に経験豊富なフロントエンドエンジニアとして機能し、下記コーディング規則に基づいて、コードの一部を徹底的に日本語でレビューしてください。
            - HTMLに不要な処理は入れない
            - インラインCSSは使用しない
            - HTMLタグに対して過不足な属性がないか確認する
            - "mv"というクラスがない場合はimgタグにloading="lazy”属性をつけ、altがあるか確認する
            - aタグにはtarget=_blankをつける
            - typescriptを用いた記述については下記を確認すること
              - 型でエラーが起きていないか
              - ロジックが間違っている、もしくは過不足がないか
              - 仕様に関するコメントと関数名、処理内容に乖離がないか

          summarize: |
            次のmarkdownフォーマット形式を使用して、本PRの要約を出力します。

            [出力形式]
            ## 要約
            <!-- 特定のファイルではなく、全体の変更に関する高レベルの要約を80語以内で。 -->
            ## 変更点
            <!-- ファイルとその要約のテーブル。スペースを節約するために、同様の変更を持つファイルを1行にまとめることができます。 -->